### ISSUE TITLE
Size of index ..... not as expected in manifest

### ISSUE THREAD

**Issue by 0x-diy** [TrueBlocks/trueblocks-core#2369] opened 2022-09-28 15:16 UTC
Moved a chat discussion to here so it's not lost.

See this screen shot...

![image](https://user-images.githubusercontent.com/86267403/192816801-5bfd4cc6-214a-44ca-8923-15f9ece37d6e.png)

Appears to be from where the scrape started after the init --all completed. This is what I saw after ran init --all  (I --- out some values as I'm not sure it they are specific to my machine)....

chifra init --all

INFO[27-09|14:07:19.566] Chain: mainnet
INFO[27-09|14:07:19.566] Gateway: https://ipfs.unchainedindex.io/ipfs/

INFO[27-09|14:07:19.566] CID: ----------------------

INFO[27-09|14:07:23.344] Unchained Index: -------------

INFO[27-09|14:07:23.344] Schemas: ------------------

INFO[27-09|14:07:23.344] Config Folder: -------/trueblocks/config/mainnet/

INFO[27-09|14:07:23.345] Index Folder: --------/unchained/mainnet/

INFO[27-09|14:07:23.345] Chunks in Manifest: 3097

INFO[27-09|14:07:23.345] Corrections Needed: 0

INFO[27-09|14:07:23.345] Completed initializing index files.

INFO[27-09|14:07:23.345] Completed initializing bloom files.
[9:35 AM]
chifra chunks index --check

INFO[27-09|14:09:23.038] Chain: mainnet

INFO[27-09|14:09:23.038] Gateway: https://ipfs.unchainedindex.io/ipfs/

INFO[27-09|14:09:23.038] CID: ----------------
{

  "data": [

    {

      "reason": "Filenames sequential",

      "nTests": 9288,

      "result": "passed"

    },

    {

      "reason": "Internally consistent",

      "nTests": 3097,

      "result": "passed"

    },

    {

      "reason": "Consistent hashes",

      "nTests": 12388,

      "result": "passed"

    },

    {

      "reason": "Check file sizes",

      "nTests": 3097,

      "result": "passed"

    },

    {

      "reason": "Remote Manifest to Cached Manifest",

      "nTests": 6194,

      "result": "passed"

    },

    {

      "reason": "Disc Files to Cached Manifest",

      "nTests": 6194,

      "result": "passed"

    },

    {

      "reason": "Disc Files to Remote Manifest",

      "nTests": 6194,

      "result": "passed"

    }

  ]

**Comment by tjayrush** [comment] 2022-10-09 02:05
This is a duplicate of https://github.com/TrueBlocks/trueblocks-core/issues/2411

**Closed as completed by tjayrush** 2022-10-09 02:05 UTC
