### ISSUE TITLE
chifra scrape - Instable node connection 

### ISSUE THREAD

**Issue by tnet-ag** [TrueBlocks/trueblocks-core#3179] opened 2023-08-25 15:04 UTC
For example when I run **chifra scrape**

It works a while then I get

`

Could not connect to RPC client Post "http://erigon.dappnode:8545": dial tcp ***: connect: cannot assign requested address

`
Then after a while it works again and so on

Could be that client or server run out of free ports?

Running against a erigon which runs on dappnode

**Comment by tnet-ag** [comment] 2023-08-25 15:06
Happens when directly installed on the machine and when running in docker with docker compose up.

**Comment by tnet-ag** [comment] 2023-08-25 15:10
Already rebooted dappnode and the server where trueblocks run

Also restarted the erigon container on dappnode

**Comment by dszlachta** [comment] 2023-08-25 15:19
It seems that this error comes directly from your operating system... Can you paste the command that you use to run TrueBlocks docker container?

**Comment by tnet-ag** [comment] 2023-08-25 15:26
its docker compose up

with the following docker-compose.yml 

```
# UPDATE_DOCKER_BUILD_VERSION
services:
  core:
    image: trueblocks/core:v0.70.0-beta
    build: ./
    env_file: .env
    ports:
      - "8080:${SERVE_PORT-8080}"
    volumes:
      - type: bind
        # The source should match the folder you made to store the cache
        source: ****/cache
        target: /cache
      - type: bind
        # The source should match the folder you made to store the Unchained index
        source: ****/unchained
        target: /unchained

    network_mode: "host"
volumes:
  unchained:
  cache:
```

**Comment by tnet-ag** [comment] 2023-08-25 15:32
same with

image: trueblocks/core:v1.0.0-release

**Comment by tnet-ag** [comment] 2023-08-25 15:36
`netstat -an | grep ESTABLISHED | wc -l `

on the server where trueblocks runs gives me 9 as output

when runing **chifra scrape**

**Comment by dszlachta** [comment] 2023-08-25 15:44
I'm not sure if it solves your issue, but where your docker-compose file says
```yaml
    ports:
      - "8080:${SERVE_PORT-8080}"
 ```
It should be `"8080:${SERVE_PORT:-8080}"` (note the **:**). Just like in this answer: https://github.com/docker/docs/issues/6914#issuecomment-398818071

**Comment by tjayrush** [comment] 2023-08-25 15:46
Hi. Just jumping in here. I've seen that error before, it usually means that Erigon is in `sync` mode, which it goes into pretty frequently. Usually, the sync mode takes only a second or two and Erigon is able to respond with valid data. Once in a while it acts like the RPC is not present.

We don't handle that case all that well -- but, what we do try to do is this. The scraper processes blocks in groups of around 2,000 (set with `--block_cnt` to the `chifra scrape` command). If, after processing all 2,000, it finds that any of them didn't get fully processed (because of an error response from the node), it starts that batch over.

I'm not sure if that has anything to do with what you're seeing or not, but it might explain why it works and then doesn't work and then works again.

**Comment by tnet-ag** [comment] 2023-08-25 18:47
@tjayrush @dszlachta

Thanks for the answers / Explaination

to rule out connection problems of the server where trueblocks is running I may will try to install trueblocks on another server.

Because Ialso get errors while download the unchained index:

WARN[25-08|18:14:30.768] Failed download  013213473-013216366  (will retry)                               
EROR[25-08|18:14:30.768] error copying 013213473-013216366 file in writeBytesToDisc: [stream error: stream ID 5039; INTERNAL_ERROR; received from peer]

But so far stuff like ping 8.8.8.8 or the node is working without interruptions
also stuff like

`watch -n 1 echo $(curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://erigon.dappnode:8545)`
does not produce errors over time.

but error correction seems to work 
the index is building up

**Comment by tjayrush** [comment] 2023-08-25 20:36
Thanks for your patience. It will be worth it, once it's caught up. The `chifra init` routine also fails once in a while, but it tries to recover in a way similar to `chifra scrape`. If it fails to download any particular chunk it will try again three time and then just fail. But...you can always re-run `chifra init` as many times as you like. It knows what it's trying to download (from the manifest), so if it does get what it's looking for (either missing or partial download) it will keep trying to download until the manifest and the files on disc match.

After `chifra init` finishes without reporting errors, you can run `chifra chunks index --check` and it should report that everything is downloaded correctly.

This is a super difficult thing to test, as you might imagine, especially on other machines. It works fairly well on our machines, but our machines and in the wild are two different things. To the extent you can help us figure it out, the better for all.

So, thanks. We appreciate your issues.

**Comment by LoboSolitario** [comment] 2023-08-27 00:08
Hey all, 
I am running into the same issue. 
My setup: 
- I am running an erigon archival node on my machine. 
- I am running trueblocks in docker.

Current issue:
- I am in the process of upgrading the trueblocks versions from v0.44.0-beta (which is also running in docker and works fine ) to v1.0.0 
- When I start the docker container using `docker-compose up`, it starts the scraping process, but after  4 process blocks of 2000 blocks, it starts giving me the error `Could not connect to RPC client Post "http://172.17.0.1:8545": dial tcp 172.17.0.1:8545: connect: cannot assign requested address` 
- Once I restart the container, it does the exact same thing. It works for maybe 2-3 process blocks and then gives me the same error.
![image](https://github.com/TrueBlocks/trueblocks-core/assets/33311245/9dc94576-4931-4b9e-ad9f-f8f1cca936bc)

**Comment by dszlachta** [comment] 2023-08-28 14:31
Thanks for reporting it. I was able to reproduce the issue, but it's tricky to find the cause and it may take some time to fix it

**Comment by dszlachta** [comment] 2023-09-05 11:48
Thank you both for your patience. I've created a PR with bugfix and hopefully it can be included in the next release.

The issue was caused by Go and `chifra` being super fast :)

**Comment by tjayrush** [comment] 2023-09-05 14:11
Hi @dszlachta. Thanks for this. Can we do a "hotfix" into `master` with this? I'm not ready to merge this into `develop`, nor is `develop` ready to be merged into `master`.

**Comment by dszlachta** [comment] 2023-09-05 14:34
@tjayrush sure, we can merge it as a hotfix, straight to `master`. I'll update the PR

**Closed as completed** 2023-09-05 15:28 UTC
Labels: enhancement, TC-apps:scrape
