### ISSUE TITLE
abi not found for manifestHashMap(0x0, "mainnet-ts")

### ISSUE THREAD

**Issue by acmLL** [TrueBlocks/trueblocks-core#3612] opened 2024-04-24 11:37 UTC
Hi,

   I followed all the installation steps but when I type: chifra blocks 12 or chifra init --all, I get: WARN[24-04|08:30:32.498] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found 
Error: the --call value provided (manifestHashMap(0x0, "mainnet")) was not found: abi not found for manifestHashMap(0x0, "mainnet"): abi not found 

I am using a MacBook Pro, Apple M1 Pro, 14.4.1 (23E224)

Thanks!

**Comment by tjayrush** [comment] 2024-04-24 11:49
Thanks so much for this. Others have reported this, so I'd really like to try to capture what's happening. Do you want to connect in Discord? I can then copy back our conclusions here so others can see it if that works.

**Comment by tjayrush** [comment] 2024-05-26 09:12
This is a duplicate of #3696.

**Closed as completed** 2024-05-26 09:13 UTC
