### ISSUE TITLE
Unsynced node causes weird error message

### ISSUE THREAD

**Issue by xianghl01** [TrueBlocks/trueblocks-core#3696] opened 2024-05-21 03:13 UTC
when I run `chifra blocks 12`,  the result is 
```
WARN[21-05|18:41:21.249] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found 
{
  "data": [],
  "errors": [
    "Post \"http://localhost:8545\": dial tcp 127.0.0.1:8545: connect: connection refused"
  ]
}
```
what should i do

**Comment by Pfed-prog** [comment] 2024-05-23 11:59
I have the same issue, It probably stems from not configuring `$CONFIG/trueBlocks.toml` from installation guide https://trueblocks.io/docs/install/install-core/

**Comment by Pfed-prog** [comment] 2024-05-23 12:46
<img width="866" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/34feb5a2-533b-4a40-8732-d7770d984809">

<img width="406" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/de052218-0c6a-47aa-8733-20d1fc59a79c">

Edit the `trueBlocks.toml` with a provider

**Comment by tjayrush** [comment] 2024-05-26 09:11
This issue is almost certainly caused by not having properly modified your configuration to point to a valid RPC provider for the Eth mainnet (Eth mainnet is the only required RPC).

You should be able to do this with `chifra config edit`.

If that doesn't work, edit the `trueBlocks.toml` file found when you enter `chifra config --paths`.

Once you're inside the `.toml` file, find the section called `[chains]`. Within that section, find a section called `[mainnet]`. Modify the `rpcProvider` to point to a valid RPC provider for mainnet Ethereum. (You can search the web for such.)

Another thing to note. In order for the `chifra init` command to work, your node must be synced to at least block 18,538,072. You will get this message if your node is not at least that far advanced.

You can check how far you're synced with `chifra when latest`.

**Comment by tjayrush** [comment] 2024-05-30 23:43
I think this is fixed. A change will come to `develop` soon (and `master` soon thereafter). I will close this in the hopes that it's fixed. If not, we can re-open it.

**Closed as completed by tjayrush** 2024-05-30 23:43 UTC
Labels: bug, priority, TC-tools:state
