### ISSUE TITLE
write to disc error recovery?

### ISSUE THREAD

**Issue by GeorgeGkinis** [TrueBlocks/trueblocks-core#3526] opened 2024-02-25 11:38 UTC
On Ubuntu when I run the following commands I get errors for some of the blooms/indices:
```
chifra init --all

WARN[25-02|12:33:56.565] Failed download  018627792-018630549  (will retry)                               
EROR[25-02|12:33:56.566] write to disc error [error copying 018627792-018630549 file in writeBytesToDisc: [stream error: stream ID 989; INTERNAL_ERROR; received from peer]]
```

I installed following the procedure on the website:
https://trueblocks.io/docs/install/install-core/

I used the main branch.

Is this error transient and will chifra retry the failed attempts?

**Comment by tjayrush** [comment] 2024-02-25 11:44
Exactly what errors are you getting?

Generally speaking, some of the errors are transient. It's almost always because of rate limiting by Pinata.

You can do `chifra init --sleep X [--all]` (where `--all` is optional, and X can be any float larger than .25).

This will slow down the query to Pinata and may help.

One nice thing about that command is that you may re-run it as many times as you wish. It will repeatedly attempt to download the exact data it needs. The routine will continue trying to download until it gets a valid index.

**Comment by tjayrush** [comment] 2024-02-25 11:44
Let me know if the above works, and please close this issue if it does. Try to give me enough information to reproduce the problem if not.

**Comment by tjayrush** [comment] 2024-03-06 01:43
I'll assume this worked and close this issue. If not, please re-open.

**Closed as completed by tjayrush** 2024-03-06 01:43 UTC
Labels: bug, TC-apps:init
